### ISSUE TITLE
Project scope

### ISSUE THREAD

**Issue by moi90** [ecotaxa/pyecotaxa#2]
Is this package only for reading/writing archive files or should it also (in the future) include an abstraction layer for the API?

**Comment by jiho** [comment]
API too, definitely.

**Comment by jiho** [comment]
The API being based on openAPI it should be able to generate a python package for it through automated tools (https://openapi-generator.tech/). But it may not be as clean and well document as a custom-made one.

**Comment by rkiko** [comment]
Hi, I generated this to include some stuff I use for the querying, but I have no real plan at the moment and no time to clean up my stuff. So, this could be sent to sleep at the moment ... Maybe should be picked up on when the API is ready, so that everything can go through that ...

**Comment by moi90** [comment]
Yes, I wouldn't want to maintain an abstraction layer for a mutating API. Once it is stable, we can start working on a Python abstraction.

**Comment by jiho** [comment]
I am starting on the R side, because to identify what needs changing we need to use it. I'll let you know after a few iterations.
