### ISSUE TITLE
Differences between pyecotaxa and ecotaxa_py_client

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [ecotaxa/pyecotaxa#7]
Hi all,

I have a question about this repository and specifically what the differences are between the ecotaxa_py_client page. I would like to be able to run an image classification algorithm on a jupyter server and maybe use this tool or the API to send the images we have collected to that server. What is the intent of pyecotaxa and what are the differences between ecotaxa_py_client?

Thanks!

Alex

**Comment by jiho** [comment]
This repository is meant to collect code written by various people to deal with EcoTaxa's TSV output. `ecotaxa_py_client` is an automatically generated package to access EcoTaxa's API.
